
services:
  - type: web
    name: hysteriaarena
    env: node
    plan: free
    buildCommand: ""
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
